### PR TITLE
WIP: Add sorting capability

### PR DESCRIPTION
**Pull request by WardLT**
Adds the ability to pass sorting commands to Search. In the process of adding this feature, I refactored the Query class.

### CODE REVIEW

**Comment by jgaff** [comment]
For clarification, is the scope of this PR just adding sort capability to Query, or should you/I add it to Forge?
Also, can you change the destination branch to `forge-dev`, please?

**Comment by WardLT** [comment]
My original plan was to just add it to Query, as my goal is to use sorting in the DLHub SDK. But, I think it'd be worthwhile to add into Forge while we're at it. Would you mind doing that?

**Comment by WardLT** [comment]
Alright, I believe I've now implementing all the requested changes. The coverage did go down, but that is likely a result of me removing a lot of code that was tested and not because the new code is untested.

**Comment by WardLT** [comment]
In short, I believe this is ready for your review before merging.

**Pull request merged**
