### PR TITLE
Add Utility for Getting Version Number

### PR DESCRIPTION
**Pull request by WardLT**
Added a short operation for getting the version number of a certain dataset.

Do you want me to test that it throws exceptions properly?

### CODE REVIEW

**Comment by WardLT** [comment]
Do we only store one version of each dataset record? If not, then this code is wrong.

**Comment by jgaff** [comment]
We (as of now) only store the latest dataset entry, so this function will work fine.
I've made one small change to the error handling - if a dataset is not found (or too many are found), it prints a message to the user and returns a sentinel value instead of raising an exception. If you think that's inappropriate for what you had in mind, we can change it back. Otherwise, I'm going to merge this in.

**Comment by WardLT** [comment]
Also, I would argue that multiple datasets matching a single name is an error we should be aware of immediately. That means reasonable search queries for matching a single dataset will silently return data from unrelated datasets. 

For that reason, I'd advocate for removing the "if you believe this is an error" clause from the multiple matches found Exception.

**Comment by jgaff** [comment]
Those are fair points. I agree about changing the error language for multiple matches; I hadn't thought of the implications there. I'm not completely convinced about raising exceptions, but since it already breaks your actual use case I'll defer to your judgement and undo my changes.

**Comment by WardLT** [comment]
What's your argument for the sentinel value? I could imagine the actual content of the Exception might get lost in the mess of a stacktrace for some users.

**Comment by jgaff** [comment]
Generally, Forge tries to be as permissive with the user as possible (ex. accepting lists and single values, adding version specifiers/wildcards onto user-provided `source_name`s, etc.), and it felt a little too harsh to make the decision for the user that a dataset-not-found result was a hard-stop error. Additionally, since Forge is meant to be used by or very close to the end-user, a `print` message would still appear before the sentinel value caused an exception further down the line.
I do understand your reasoning, and I'm not completely convinced that _not_ raising an exception is the best route either. I think since you're an actual user of Forge giving this feedback, we should minimize astonishment (and frustration) for your case.

**Pull request merged**
